"""Format analysis results into a GitHub PR comment."""

MARKER = "<!-- loopsleuth-report -->"


def format_comment(issues: list[dict]) -> str:
    """Build a markdown comment from analysis results."""
    total_issues = sum(
        len(f["issues"]) for file in issues for f in file["results"]
    )
    total_funcs = sum(len(file["results"]) for file in issues)
    total_files = len(issues)

    lines = [
        MARKER,
        "## LoopSleuth Performance Analysis",
        "",
        f"Found **{total_issues} issue(s)** in "
        f"**{total_funcs} function(s)** across "
        f"**{total_files} file(s)**.",
        "",
    ]

    for file in issues:
        path = file["path"]
        file_issue_count = sum(len(f["issues"]) for f in file["results"])
        lines.append(
            f"<details>\n<summary><b>{path}</b> "
            f"&mdash; {file_issue_count} issue(s)</summary>\n"
        )

        for func in file["results"]:
            name = func["function_name"]
            cls = func.get("class_name")
            display = f"{cls}.{name}" if cls else name
            line_num = func.get("line_number", "?")

            for issue in func["issues"]:
                check = issue.get("check_name", issue.get("check_key", "?"))
                confidence = issue.get("confidence", 0)
                solution = issue.get("solution")

                lines.append(f"### `{display}` (line {line_num})")
                lines.append("")
                lines.append(
                    f"**{check}** (confidence: {confidence}%)"
                )
                lines.append("")

                if solution:
                    lines.append(
                        "<details>\n<summary>Suggested fix</summary>\n"
                    )
                    lines.append(solution)
                    lines.append("\n</details>\n")

        lines.append("</details>\n")

    lines.append("---")
    lines.append(
        "*Generated by [LoopSleuth]"
        "(https://github.com/tarekziade/loopsleuth)*"
    )
    return "\n".join(lines)


def format_clean_comment() -> str:
    """Comment body when no issues are found."""
    return (
        f"{MARKER}\n"
        "## LoopSleuth Performance Analysis\n\n"
        "No performance issues detected in the changed Python functions.\n\n"
        "---\n"
        "*Generated by [LoopSleuth]"
        "(https://github.com/tarekziade/loopsleuth)*"
    )
